version: '3.8'

services:
  backend:
    image: houssienzd/final-project-laravel-image:latest
    environment:
      - LARAVEL_DATABASE_HOST=db
      - LARAVEL_DATABASE_NAME=secure_voting_system
      - LARAVEL_DATABASE_USER=root
      - LARAVEL_DATABASE_PASSWORD=1234
      - LARAVEL_DATABASE_PORT_NUMBER=3306
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: houssienzd/final-project-react-image:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234 
      - MYSQL_DATABASE=secure_voting_system
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: