version: '3.8'

services:
  backend:
    image: houssienzed/final_project_laravel_image:latest
    environment:
      - DBBASE_HOST: db
      - DB_DATABASE: ${{ secrets.DB_NAME }}
      - DB_USERNAME: ${{ secrets.DB_USER }}
      - DB_PASSWORD: ${{ secrets.DB_PASS }}
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: houssienzed/final_project_react_image:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASS}}
      - MYSQL_DATABASE: ${{ secrets.DB_NAME}}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: