services:
  backend:
    image: ${DOCKERHUB_USERNAME:-username}/final_project_laravel_image:latest
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=secure_voting_system
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - APP_ENV=production
      - APP_DEBUG=tru
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    image: ${DOCKERHUB_USERNAME:-username}/final_project_react_image:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234 
      - MYSQL_DATABASE=secure_voting_system
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
