name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, ctype, fileinfo, openssl, pdo, mysql, tokenizer, xml, gd
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Configure and test Laravel
        run: |
          cp .env.testing .env
          composer install --prefer-dist --no-progress
          php artisan config:clear
          php artisan key:generate --env=testing
          php artisan jwt:secret --force --env=testing
          php artisan config:cache
          php artisan migrate --env=testing
          php artisan test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Laravel image
        working-directory: server
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/final_project_laravel_image:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/final_project_laravel_image:latest

      - name: Build and push React image
        working-directory: client
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/final_project_react_image:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/final_project_react_image:latest

  Copy-docker-compose-to-EC2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy docker-compose to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yaml"
          target: "/home/${{ secrets.EC2_USER }}/"

  Deploy-Laravel-Docker:
    runs-on: ubuntu-latest
    needs: Copy-docker-compose-to-EC2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker-compose down
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/final_project_laravel_image:latest
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/final_project_react_image:latest
            docker-compose up -d
            docker exec -it ubuntu_backend_1 php artisan migrate
