name: Deploy Laravel + React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Only checkout code (no PHP/Node setup needed)
      - name: Checkout code
        uses: actions/checkout@v3

      # # Optional: Run tests inside a temporary container (if needed)
      # - name: Run Laravel tests
      #   env:
      #     DB_CONNECTION: mysql
      #     DB_DATABASE: secure_voting_system_testing
      #     DB_USERNAME: ${{ secrets.DB_USERNAME }}
      #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      #   working-directory: ./server
      #   run: |
      #     docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit

      # Deploy to EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yaml"
          target: "~/"

      # Install Docker (if missing on EC2)
      - name: Install Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if ! command -v docker &> /dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y docker.io docker-compose
              sudo usermod -aG docker $USER
              newgrp docker
            fi

      # Run migrations + start containers
      - name: Deploy with Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/secure-voting-system
            docker-compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/react:latest #laravel image name
            docker rmi ${{ secrets.DOCKER_USERNAME }}/react:latest #react image name
            docker-compose up -d
            docker exec laravel-container php artisan migrate --force
