name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: secure_voting_system_testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, ctype, fileinfo, openssl, pdo, mysql, tokenizer, xml, gd
          coverage: none

      - name: Install Composer dependencies
        working-directory: server
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Configure and test Laravel
        working-directory: server
        run: |
          cp .env.testing .env
          php artisan config:clear
          php artisan key:generate --env=testing
          php artisan config:cache
          php artisan migrate --env=testing
          php artisan test

  build-and-push-laravel-image:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build laravel image
        working-directory: server
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/final_project_laravel_image:latest .

      - name: Push laravel image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/final_project_laravel_image:latest

  build-and-push-react-image:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build react image
        working-directory: client
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/final_project_react_image:latest .

      - name: Push react image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/final_project_react_image:latest

  Copy-docker-compose-to-EC2:
    needs: [build-and-push-react-image, build-and-push-laravel-image]
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker Compose on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker-compose-plugin

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy docker-compose to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yaml"
          target: "/home/${{ secrets.EC2_USER }}/"

  Deploy-Laravel-Docker:
    runs-on: ubuntu-latest
    needs: Copy-docker-compose-to-EC2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Create .env file for docker-compose
            cat > .env << EOL
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            APP_NAME=Laravel
            APP_ENV=production
            APP_KEY=base64:ql0FVsSE4p7sS6kjA8PjJYRRZaq/RWPfFInBybCtnwo= 
            APP_DEBUG=false
            APP_URL=http://13.36.171.143

            LOG_CHANNEL=stack
            LOG_LEVEL=debug

            # Database
            DB_CONNECTION=mysql
            DB_HOST=db
            DB_PORT=3306
            DB_DATABASE=secure_voting_system
            DB_USERNAME=root
            DB_PASSWORD=1234

            # Caching/Session
            CACHE_DRIVER=file
            QUEUE_CONNECTION=sync
            SESSION_DRIVER=file
            SESSION_LIFETIME=120

            # JWT Settings (required for tymon/jwt-auth or open-source-saver/jwt-auth)
            JWT_SECRET=eQRlE1aUEl1aLci6HZv8WAZhLwIdqd3OHgYWnctIukVxBGDa85WnKTMAukEoSzkd
            JWT_TTL=60         # Token time-to-live in minutes (optional)

            JWT_ALGO=HS256

            OPENAI_API_KEY=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

            EOL

            # Login to Docker Hub first
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # Pull images
            docker compose pull

            # Stop existing containers
            docker compose down

            # Remove old images
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/final_project_laravel_image:latest || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/final_project_react_image:latest || true

            # Start containers
            docker compose up -d

            # Wait for containers to start
            sleep 30

            # Get backend container ID
            BACKEND_CONTAINER=$(docker ps -qf "name=backend")
            if [ -z "$BACKEND_CONTAINER" ]; then
              echo "Backend container not found!"
              docker ps -a
              exit 1
            fi

            # Run migrations
            docker exec $BACKEND_CONTAINER php artisan migrate:fresh --seed --force

             # If fails, show error logs
            if [ $? -ne 0 ]; then
              echo "Migration failed! Showing logs:"
              docker logs $BACKEND_CONTAINER | grep -i error
              exit 1
            fi

            # Clean up unused images
            docker image prune -a -f

# docker-compose down
#             docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/final_project_laravel_image:latest
#             docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/final_project_react_image:latest
#             docker image prune -a -f
#             docker-compose up -d
#             sleep 10  # Wait for containers to start
#             docker exec $(docker ps -qf "name=backend") php artisan migrate

